name: Build iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Configurar Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios,aarch64-apple-ios-sim

      - name: Instalar CocoaPods
        run: |
          brew install cocoapods

      - name: Inicializar proyecto iOS
        run: npx tauri ios init

      - name: Construir aplicación iOS
        run: npx tauri ios build

      - name: Buscar IPA
        run: |
          find src-tauri/gen/apple -name "*.ipa" -print

      - name: Guardar IPA
        uses: actions/upload-artifact@v4
        with:
          name: Partidos-Enigma-iOS
          path: |
            src-tauri/gen/apple/**/*.ipa
